version: '3.8'

services:
  trustlist-service:
    build: .
    container_name: trustlist-service
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/usr/src/app/.env
      - ./data-repo:/usr/src/app/data-repo
      - ./private_key.pem:/usr/src/app/private_key.pem
      - ./public_key.pem:/usr/src/app/public_key.pem
      # Mount host's Git config so git operations inside container know user details
      - ~/.gitconfig:/root/.gitconfig:ro
